spring.main.allow-bean-definition-overriding: true

server:
  port: 18210

spring:
  application:
    name: docs-document-processor
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

info:
  app:
    name: Сервис обработки документов
    description: Сервис для сохранения документов в хранилище и их выдачи в нужном формате
    version: "@project.version@"